// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoufXlPYabGVUJVzr1cvlAVhBr7Q2wItA',
    appId: '1:177201101141:web:bfb78f9515968478d1d7dc',
    messagingSenderId: '177201101141',
    projectId: 'my-project-social-network-237',
    authDomain: 'my-project-social-network-237.firebaseapp.com',
    storageBucket: 'my-project-social-network-237.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFzYI4UeUW-whuVIq8pXLt1suMaB70G_I',
    appId: '1:177201101141:android:1c41ea0608385813d1d7dc',
    messagingSenderId: '177201101141',
    projectId: 'my-project-social-network-237',
    storageBucket: 'my-project-social-network-237.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARR59a5jKvcVeR8Q7F_DjE_jfER2pqC7E',
    appId: '1:177201101141:ios:664ac4c79a7fdee4d1d7dc',
    messagingSenderId: '177201101141',
    projectId: 'my-project-social-network-237',
    storageBucket: 'my-project-social-network-237.firebasestorage.app',
    iosBundleId: 'com.example.projetReseauSocial',
  );

}